### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by johanhaleby** [gpaumier/fumseck#3]
I don't understand how to build and install this theme. Wordpress requires a zip file for custom theme uploading so how do I package the files in this repo to a working wordpress zip file? If I just zip the entire repo and upload it won't work (just a blank screen). Any hints on to do this would be very appreciated.

**Comment by gpaumier** [comment]
This theme was written for a specific site and doesn't support third-party sites. I've updated the README to make this clearer.
